---
kind: wcpCluster
metadata:
  vcenter: vcenter.lab.crdant.net
  datacenter: garage
  cluster: homelab                             
spec:
  ncp_cluster_network_spec:
    nsx_edge_cluster:                                   # LEAVE BLANK
    cluster_distributed_switch:                         # LEAVE BLANK
    egress_cidrs:
    - address: 10.16.4.1
      prefix: 24                                        
    ingress_cidrs:
    - address: 10.16.3.1
      prefix: 24                                        
    pod_cidrs:
    - address: 10.244.0.0                               
      prefix: 21                                        
  service_cidr:
    address: 10.96.0.0                                  
    prefix: 24                                          
  worker_DNS:
  - 10.18.1.1
  master_DNS:
  - 10.18.1.1
  master_DNS_search_domains:
  - lab.crdant.net
  master_NTP_servers:
  - 10.18.1.1
  Master_DNS_names:
  - supervisor.lab.crdant.net
  master_management_network:
    address_range:
      gateway: 10.18.1.1
      starting_address: 10.18.1.41
      subnet_mask: 255.255.255.0                        
      address_count: 5                                  
    mode: STATICRANGE                                   
    network: management-pg 
  ephemeral_storage_policy: vsan
  image_storage:
    storage_policy: vsan
  master_storage_policy: vsan
  network_provider: NSXT_CONTAINER_PLUGIN               
  size_hint: TINY
  login_banner:
  default_kubernetes_service_content_library: tanzu-kubernetes-grid