---
kind: wcpContentLibrary
metadata:
  vcenter: vcenter.lab.crdant.net
  datacenter: garage
  cluster: homelab                             
spec:
  name: tanzu-kubernetes-grid
  description: "Latest Tanzu Kubenetes Grid templates"
  storage_backings:
    - datastore_id: vsanDatastore
      type: "DATASTORE"
  type: SUBSCRIBED
  subscription_info:
    authentication_method: NONE
    ssl_thumbprint: 56:53:d1:6f:ce:b9:c1:c9:25:d5:7f:41:11:df:7b:00:2c:97:bf:95
    automatic_sync_enabled: True
    subscription_url: "https://wp-content.vmware.com/v2/latest/lib.json"
    on_demand: False
